### ISSUE TITLE
introduction: electrifier

### ISSUE THREAD

**Issue by tajbender** [microsoft/hack-together#38] opened 2023-03-01 17:07 UTC
### Project name

electrifier

### Description

integrated desktop enhancement

### Repo URL

https://github.com/electrifier/electrifier

### Team members

tajbender, harborsiem

**Comment by waldekmastykarz** [comment] 2023-03-02 08:04
Thanks for submitting your project @tajbender. Would you mind explaining a bit what your hack is doing and how it's using Microsoft Graph?

**Comment by tajbender** [comment] 2023-03-02 11:00
Hi, @waldekmastykarz,

@electrifier is a project i've been working on in my spare time for some years now.

I've re-written several parts many times. It's just a fun project to test out what's happening in .net - world. The Original .net-version just brought tab-support to _Windows File Explorer_ 🙌 🎉. 

When I heard about WinApp SDK last year, I was very excited. I never used WPF for perfomance reasons, but I love WinUI. I also like using [@dahall/Vanara](https://github.com/dahall/Vanara) from @dahall. It's a great project, for everyone who's interested. It's not _that other WinAPI-Abstraction Layer_ but a complete shell around about every API. And It's a great source for good practices.

[Graph](https://developer.microsoft.com/de-de/graph/) will be used for _Cloud Features_:

have a history of when I have worked on or with 
- that project, 
- that document, 
- on this device.

Those cloud features are still WIP. But I think, Microsoft Graph sounds the place to store the database stuff I want to collect and analyze.

Thanks for reading,
  regards,
  tajbender

**Comment by waldekmastykarz** [comment] 2023-03-02 12:46
Cool! Thanks for additional information. Looking forward to seeing how you incorporate Microsoft Graph in your project. Please, don't hesitate to reach out if you've got any questions.

**Comment by tajbender** [comment] 2023-03-13 17:44
@waldekmastykarz:
I'm a sorry, I had a flue the last days, but I'm still hacking and confident that 'll get something up and running, although not as much as I hoped.

However, thanks to the team for this great contest!

**Comment by waldekmastykarz** [comment] 2023-03-14 07:42
Ouch, sorry to hear that @tajbender. I appreciate you hacking away despite being under the weather. I hope you'll feel better soon.

**Comment by tajbender** [comment] 2023-03-14 08:33
I appreciate that @waldekmastykarz.
I'm already feeling better, Thanks.

_Just a side note:_ I've found something on my attic.

To be honest, this is the second time I'm taking part in such a Microsoft Hackaton 🎉 🤚...

...but last time has been a long time ago 🗓️ 😁 

![IMG_20230314_091944](https://user-images.githubusercontent.com/10961499/224940877-f584e72f-c1be-47c3-a0db-8ea2215c70de.jpg)

**Comment by waldekmastykarz** [comment] 2023-03-14 09:59
Wow! This is truly a blast from the past! 😄

**Comment by tajbender** [comment] 2023-03-15 08:03
Note to @tajbender: Build succeeded:

https://dev.azure.com/electrifier/electrifier/_build/results?buildId=3&view=results

**Comment by waldekmastykarz** [comment] 2023-03-16 07:28
duplicate of #188

**Closed by waldekmastykarz** 2023-03-16 07:28 UTC
Labels: duplicate

**Comment by tajbender** [comment] 2023-03-16 08:56
[...to be continued...](https://github.com/microsoft/hack-together/issues/188)
