### ISSUE TITLE
Project: <Hack-together>

### ISSUE THREAD

**Issue by kusscaroline** [microsoft/hack-together#220] opened 2023-03-16 23:28 UTC
### Project name

Weather Dress Code- Test

### Description

Praise the Lord, my to God!
I have finally figured out the problems:
First of all - I had chosen a multi-tenant settings, hence it enforces a need to verify.
Second - Since I was using the Ms365 toolkit, everything automated and set on rock (in the Azure Manifest)
Third - Ms Identity platform messed up my user accounts and uploaded the App using a different logging from the one (test) I had set up on Ms 365, the tenant was different and so, once I had tried a few times to log on, it seemed to locked out the account. Although, I can get in now, Azure is holding that App ransom and I cannot modify it.

Here is a test run with a new test app - working.
https://blazorapp320230316224804.azurewebsites.net

Please, kindly consider it that I had submitted my App on time, except for those issues that were not in my control.
Regards
Caroline

### Repo URL

https://blazorapp320230316224804.azurewebsites.net

### Team members

Caroline Manta

**Comment by waldekmastykarz** [comment] 2023-03-17 12:47
Duplicate of #193

**Closed as not planned by waldekmastykarz** 2023-03-17 12:47 UTC
Labels: duplicate
